name: route-to-specialist
description: Route requests to appropriate specialist under architect
trigger: /architect
steps:
- name: analyze-request
  agent: leader-architect
  action: Analyze request and determine appropriate specialist
  output: routing_decision
- name: route-to-specialist
  agent: specialist-{{routing_decision.specialist_id}}
  action: Execute specialist work
  input: '{{request}}'
  output: specialist_result
- name: synthesize-response
  agent: leader-architect
  action: Review and synthesize specialist output
  input: '{{specialist_result}}'
  output: final_response
