name: architect-complete
description: Complete architect workflow with validation
phase: 3-arch
trigger: /architect-complete
steps:
- name: analyze-request
  agent: leader-architect
  action: Analyze request and determine specialist
  output: routing_decision
- name: route-to-specialist
  agent: specialist-{{routing_decision.specialist_id}}
  action: Execute specialist work
  input: '{{request}}'
  output: specialist_result
- name: leader-review
  agent: leader-architect
  action: Review and validate specialist output
  input: '{{specialist_result}}'
  output: review_result
- name: finalize
  agent: leader-architect
  condition: '{{review_result.approved}}'
  action: Finalize and synthesize response
  input: '{{review_result}}'
  output: final_response
integration:
  customize_file: _bmad/_config/agents/custom-architect-leader.customize.yaml
  menu_trigger: architect-complete
  description: Complete architect workflow with validation
